apiVersion: v1
kind: Service
metadata:
  name: session-gateway
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: session-gateway-placeholder # Dummy selector for now
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx-gateway-placeholder # Dummy selector for now
