apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: budget-analyzer-gateway
  namespace: default
spec:
  gatewayClassName: envoy-proxy
  listeners:
  - name: https
    hostname: "*.budgetanalyzer.local"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: budgetanalyzer-local-wildcard-tls
    allowedRoutes:
      namespaces:
        from: Same
